#!/bin/bash

h=$(date +%H)

if [ $h -lt 12 ]; then
    echo "Good Morning"
elif [ $h -lt 17 ]; then
    echo "Good Afternoon"
elif [ $h -lt 21 ]; then
    echo "Good Evening"
else
    echo "Good Night"
fi
